<a href="https://colab.research.google.com/github/Seblao/Projet-Air-BnB/blob/main/1_2_Pandas_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [9]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user')
df

          1|24|M|technician|85711
0              2|53|F|other|94043
1             3|23|M|writer|32067
2         4|24|M|technician|43537
3              5|33|F|other|15213
4          6|42|M|executive|98101
..                            ...
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

[942 rows x 1 columns]

In [10]:
df.tail()

          1|24|M|technician|85711
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

In [18]:
df.head()

   1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [16]:
df.dtypes

1|24|M|technician|85711    object
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   1|24|M|technician|85711  942 non-null    object
dtypes: object(1)
memory usage: 7.5+ KB

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv')
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,South America
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [21]:
df.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [22]:
df.set_index('country', inplace=True)
df

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [23]:
zimbabwe_row = df.loc['Zimbabwe']
zimbabwe_row

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [24]:
columns_continent = df.loc['Zimbabwe', 'continent']
columns_continent

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [36]:
df

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

In [51]:
# Aucune idée

In [43]:
df.rename(columns={'beer_servings':'beer', 'spirit_servings': 'spirit', 'wine_servings': 'wine', 'total_litres_of_pure_alcohol' : 'pur_alcohol', 'continent': 'World'})

             beer  spirit  wine  pur_alcohol          World
country
Afghanistan     0       0     0          0.0           Asia
Albania        89     132    54          4.9         Europe
Algeria        25       0    14          0.7         Africa
Andorra       245     138   312         12.4         Europe
Angola        217      57    45          5.9         Africa
...           ...     ...   ...          ...            ...
Venezuela     333     100     3          7.7  South America
Vietnam       111       2     1          2.0           Asia
Yemen           6       0     0          0.1           Asia
Zambia         32      19     4          2.5         Africa
Zimbabwe       64      18     4          4.7         Africa

[193 rows x 5 columns]

In [27]:
df

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [28]:
df.iloc[:3]

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa

# Mission 7

Achieve the same result as in mission 6 by using loc

In [29]:
df.loc[df.index[:3]]

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa